<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2020 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Distribution License v. 1.0, which is available at
    http://www.eclipse.org/org/documents/edl-v10.php.

    SPDX-License-Identifier: BSD-3-Clause

-->

<definitions
  name="AddressTest"
  targetNamespace="urn:test"
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:types="urn:test:types"
  xmlns:tns="urn:test">

  <types>
     <xsd:schema>
          <xsd:import namespace="urn:test:types" schemaLocation="address.xsd"/>
     </xsd:schema>
  </types>

  <wsp:Policy xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="wsaddr_policy" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
     <wsaw:UsingAddressing xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"/>
  </wsp:Policy>

  <message name="AddressRequest">
    <part name="parameters" element="types:Address"/>
    <part name="header" element="types:Address"/>
  </message>

  <message name="AddressResponse">
    <part name="parameters" element="types:AddressResponse"/>
  </message>

  <portType name="Address">
    <operation name="hello">
      <input message="tns:AddressRequest"/>
      <output message="tns:AddressResponse"/>
    </operation>
  </portType>

  <binding name="AddressBinding" type="tns:Address">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#wsaddr_policy" required="false"/>
    <operation name="hello">
      <soap:operation soapAction="urn:test:hello"/>
      <input>
        <soap:body parts="parameters" use="literal"/>
        <soap:header message="tns:AddressRequest" part="header" use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>

  </binding>

  <service name="Address">
    <port name="AddressPort" binding="tns:AddressBinding">
      <soap:address location="http://test.org/hello"/>
    </port>
  </service>

</definitions>
